name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
  
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Generate runner lock file and install
      run: |
        rm -f poetry.lock
        poetry lock
        poetry install --no-interaction --no-root

    - name: Run code quality checks (Linting)
      run: poetry run flake8 src/
    
    - name: Run Tests
      run : poetry run pytest tests/